server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/lottery?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:/mybatis/mapper/*.xml
  mapper-locations: classpath:/mybatis/config/mybaits-config.xml


dubbo:
  application:
    name: Lottery
    version: 1.0.0
  registry:
    address: N/A #multicast://224.5.6.7:1234
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.itwang.lottery.rpc